name: CI
on:
  push:
    branches:
      - dev
      
jobs:
  build:
    runs-on: ubuntu latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Semantic Versioning
        id: versioning
        uses: paulhatch/semantic-version@v4.0.3
        with:
          branch: dev
          tag-prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-SNAPSHOT${increment}"
          
